### ISSUE TITLE
GDAPI.Application.Database#WriteLevelData blanks CCLocalLevels.dat

### ISSUE THREAD

**Issue by ascpixi** [AlFasGD/GDAPI#65]
Hi! ヾ(^▽^)
I was trying to use this API, but I've encountered an issue while trying to write the level data.
The method [`Database.WriteLevelData`](https://github.com/AlFasGD/GDAPI/blob/master/GDAPI/GDAPI/Application/Database.cs#L450) blanks the `%localappdata%/GeometryDash/CCLocalLevels.dat` file, making it 0 bytes.

My code is split into two classes. I'm using WPF, so adding all the code for a simple example would be pretty redundant, so here's a simplified version!
```cs
class Class1{
     public static Database GDDatabase {get; private set;}
     public static bool LocalLevelsLoaded {get; private set;}

     static{
          GDDatabase = new Database();

          GDDatabase.LevelDataSetCompleted += () => {
                LocalLevelsLoaded = true;
          };
     }
}
```

```cs
class Class2{
      public async void Main(Level level){
             while(!Class1.LocalLevelsLoaded) { Thread.Sleep(25); }
             await level.InitializeLoadingLevelString();
             Class1.GDDatabase.WriteLevelData();
      }
}
```

Calling `Class2.Main` blanks out the `CCLocalLevels.dat` file, even when no apparent level modifications have been made.

If it helps, I'm using WPF and using a [`ListView`](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/listview-overview?view=netframeworkdesktop-4.8) with its [`ItemsSource`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.itemscontrol.itemssource?view=net-5.0) set to a **copy** of `Class1.GDDatabase.UserLevels` (copied by doing `new List<Level>(Class1.GDDatabase.UserLevels)`)

Thank you! (◠‿◠)

**Comment by ascpixi** [comment]
Oh, sorry!
I've taken the time to write actual reproduction code:
[GDAPIReproCase.zip](https://github.com/AlFasGD/GDAPI/files/7280449/GDAPIReproCase.zip) (NET Core 3.1)

On my machine, compiling and running it returns this:
![image](https://user-images.githubusercontent.com/44982772/135905261-91836dec-29e7-4365-a01d-23da9e10dc07.png)

Which means that everything else works just fine - except `CCLocalLevels.dat` is 0 bytes.

Thank you!

**Comment by AlFasGD** [comment]
Turns out it was a general error that was introduced after wrapping the level data information. This is broken for literally everything and everyone, silently blanking the gamesave.

I greatly appreciate you brought this issue forth. Will push a fix in a few minutes, and make a new release for that purpose.

Btw, .NET Core 3.1 is not the issue. You may use anything that is above .NET Core 3.1, including .NET 5.0 and .NET 6.0, and the library will be properly supported. Using .NET Core 3.0 and below though will not be supported, as its end-of-life has passed.

**Comment by AlFasGD** [comment]
Issue fixed in the most recent commits, please ensure you update the package to its latest version, once it becomes available. This issue will be closed the moment the package is uploaded and the older version becomes deprecated.

**Comment by naoei** [comment]
Apologies for being rather late, I've uploaded a new [NuGet package](https://www.nuget.org/packages/GDAPI/1.2.1) that includes this fix. Please check and make sure that it is now working for you.

**Comment by ascpixi** [comment]
Yep, works fine now! Thank you!
