### ISSUE TITLE
Triggers with decimal values get interpreted as integers

### ISSUE THREAD

**Issue by ascpixi** [AlFasGD/GDAPI#66]
Hello again! ヾ(^▽^)
If a trigger has a property with its value being a decimal, the property gets converted into a whole number (integer).

For example: a pulse trigger has its "Fade In" property set to "7.27". When this property is accessed through GDAPI (`PulseTrigger`), the value of `FadeIn` is "727".

Values like "5" are unaffected, as they aren't a decimal.
Values like "5.5" get converted to "55".
Values like "0.05" get converted to "5". 

Thanks! (^▽^)

**Comment by AlFasGD** [comment]
After looking through the code, it was found that there has carelessly been lack of culture invariance. This results in ignoring the actual separator if your system culture is not compatible. In fact, there's tons of warnings about this in the entire project. A fix is being pushed for this specific case, and a long-time solution will be an open issue for somebody to fix through a PR.
